### ISSUE TITLE
Can you add a “poster ” property?

### ISSUE THREAD

**Issue by cn-jiangfei** [iametza/ckeditor-html5-audio#17]
hi @aldatsa  ！
Thank you very much for the html5video plugin，But there is no poster attribute，Can you add a poster upload and URL attribute?

**Comment by cn-jiangfei** [comment]
@aldatsa

**Comment by aldatsa** [comment]
Hi @cn-jiangfei,
this is the repository of the CKEditor HTML5 Audio plugin. I see that you created an issue in the repository of the CKEditor HTML5 Video plugin: [bahriddin/ckeditor-html5-video#7](https://github.com/bahriddin/ckeditor-html5-video/issues/7), so I'm going to close this issue.
Best regards

**Comment by cn-jiangfei** [comment]
@aldatsa Can you help me with this question?

**Comment by aldatsa** [comment]
@bahriddin created the video plugin based on our plugin. I think that he is the most appropriate person to handle this issue. I don't know him personally. There's an email address in his github profile, you could try to contact him:
https://github.com/bahriddin/

**Comment by cn-jiangfei** [comment]
我明白了，感谢！
I see. Thank you!
