### ISSUE TITLE
Error using html5audio plugin

### ISSUE THREAD

**Issue by pmassu** [iametza/ckeditor-html5-audio#19]
Insert an audio file (uploading it or defining the url) in a document

Expected result:
Audio plugin appears in the document and i can hear the audio.
I can save the document.

Actual result:
Audio plugin appears in the document and i can hear the audio.
It is impossible to save the document. Attached the error message i obtain.

Other details:
Browser: Chrome
OS: Debian
CKEditor version: 4.5.7
Installed CKEditor plugins: save,filebrowser,colorbutton,panelbutton,html5audio,widget,lineutils,clipboard,widgetselection
![screen shot 06-09-17 at 12 01 pm](https://user-images.githubusercontent.com/15627951/26971307-e8d18258-4d0c-11e7-80a5-57cd77f052e3.PNG)

**Comment by aldatsa** [comment]
I have never used the save plugin. Is it this one http://ckeditor.com/addon/save?
I'm quite busy at the moment but I'll try to fix the issue when I have time.

**Comment by pmassu** [comment]
Well, i finaly managed to have it work.
Strange behaviour with dependencies on colorbutton plugin. Need to have it deployed but not declared ckeditor config.

**Comment by pmassu** [comment]
One question about html5audio plugin, is there a way to hide some functions from control panel displayed to the end user (like the download button)?

**Comment by aldatsa** [comment]
Currently no but it could be an useful feature. The ControlsList API looks good: https://googlechrome.github.io/samples/media/controlslist.html

**Comment by aldatsa** [comment]
@mnakalay created a pull request (#21) that implements the functionality that you requested @pmassu. It's available in the version 1.4.0 that we have just released:
http://ckeditor.com/addon/html5audio
