### ISSUE TITLE
Html5audio doesn't work with Drupal CKEditor module

### ISSUE THREAD

**Issue by timmerk** [iametza/ckeditor-html5-audio#22]
I tried version 1.4.0 on both CKEditor 4.5 and 4.7 with the Drupal CKEditor module. The module shows up in the Drupal CKEditor GUI, and I can enable it, but html5audio icon wont show up in the list of Available toolbar icons, even if I manually add it to the toolbars in ckeditor.config.js.

**Comment by aldatsa** [comment]
I'm sorry @timmerk but I have never used Drupal and I don't know why Html5audio doesn't work with the Drupal CKEditor module.

Have you installed html5audio's dependencies? This question looks similar:
https://drupal.stackexchange.com/questions/171358/ckeditor-configured-mediaembed-button-doesnt-appear-in-toolbar

The dependencies are: [widget](https://ckeditor.com/addon/widget), [lineutils](https://ckeditor.com/addon/lineutils), [clipboard](https://ckeditor.com/addon/clipboard), [widgetselection](https://ckeditor.com/addon/widgetselection), [notification](https://ckeditor.com/addon/notification), [toolbar](https://ckeditor.com/addon/toolbar), and [button](https://ckeditor.com/addon/button).
