### ISSUE TITLE
Problem with icon?

### ISSUE THREAD

**Issue by MichaelOCONN** [iametza/ckeditor-html5-audio#5]
I've installed the files into plugins, and added the call in config.extraPlugins.  I've added 'html5audio' to the toolbar, but the icon doesn't show up.  My installation has widgets and other plutings are functioning with similar installations.  Any suggestions?

Thanks,
Michael

**Comment by aldatsa** [comment]
Hi Michael,

are you using a custom toolbar? In that case you should use 'Html5audio' (note that the first letter is uppercase).

For example:

```
CKEDITOR.editorConfig = function( config ) {
    config.toolbar = [
        ...
        { name: 'insert', items: [ 'Html5audio', 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] }
        ...
    ];
};
```

Best regards
