### ISSUE TITLE
Review Russian translation

### ISSUE THREAD

**Issue by aldatsa** [iametza/ckeditor-html5-audio#6]
Hi @smartcorestudio,

I don't want to bother you but we are going to release a new version soon. The main improvement is a new tab for advanced options that includes the option to set the autoplay attribute of the audio tag. We added some new new strings, can you please review and correct them?

Thank you very much!

**Comment by smartcorestudio** [comment]
Hi @aldatsa! Everything is fine! Can't wait for the new version! Thanks for your work!

**Comment by aldatsa** [comment]
Hi @smartcorestudio. The new version is available. Thank you for your help!
